### ISSUE TITLE
Name change proposal

### ISSUE THREAD

**Issue by daschy** [Jaennaet/pISSStream#4]
For the sake of naming convention with other selfhosted services. I propose to change the name to urinarr or another name that ends with arr

Merry Xmas

**Comment by Jaennaet** [comment]
Self-hosted? I… uh, it's a native application that uses an official telemetry stream provided by Lightstreamer, so there's not much that's self-hosted here 😀

And pISSStream has *brand recognition*! We can't just go changing the name, we're famous!

Closing, but I unironically applaud the enthusiasm.
